# Generated by Django 5.0 on 2024-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('id', models.BinaryField(db_column='_IDRRef', max_length=16, primary_key=True, serialize=False, unique=True)),
                ('reproduction', models.BinaryField(blank=True, db_column='_Fld3203RRef', max_length=16, null=True)),
                ('display_name', models.CharField(db_column='_Description', max_length=100)),
            ],
            options={
                'db_table': 'my_type_of_production',
                'managed': False,
            },
        ),
    ]
